services:
  sht-analyzer-db:
    image: postgres:16.1
    container_name: postgres-sht-analyzer-db
    ports:
      - "5469:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-analyzer-service
      - POSTGRES_DB=sht-analyzer-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  sht-shopping-store-db:
    image: postgres:16.1
    container_name: postgres-sht-shopping-store-db
    ports:
      - "5470:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-shopping-store-service
      - POSTGRES_DB=sht-shopping-store-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  sht-shopping-cart-db:
    image: postgres:16.1
    container_name: postgres-sht-shopping-cart-db
    ports:
      - "5471:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-shopping-cart-service
      - POSTGRES_DB=sht-shopping-cart-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  sht-warehouse-db:
    image: postgres:16.1
    container_name: postgres-sht-warehouse-db
    ports:
      - "5472:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-warehouse-service
      - POSTGRES_DB=sht-warehouse-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  sht-order-db:
    image: postgres:16.1
    container_name: postgres-sht-order-db
    ports:
      - "5473:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-order-service
      - POSTGRES_DB=sht-order-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  sht-delivery-db:
    image: postgres:16.1
    container_name: postgres-sht-delivery-db
    ports:
      - "5474:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-delivery-service
      - POSTGRES_DB=sht-delivery-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  sht-payment-db:
    image: postgres:16.1
    container_name: postgres-sht-payment-db
    ports:
      - "5475:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres-sht-payment-service
      - POSTGRES_DB=sht-payment-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic telemetry.sensors.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.snapshots.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.hubs.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true