server.port=0

spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5472/sht-warehouse-service
spring.datasource.username=postgres-sht-warehouse-service
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true