server.port=0

spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5474/sht-delivery-service
spring.datasource.username=postgres-sht-delivery-service
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true