#grpc.server.port=59091

#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=ru.practicum.sht.broker.CollectorAvroSerializer

spring.application.name=collector
spring.config.import=configserver:http://localhost:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.useRandomPolicy=true
spring.cloud.config.retry.max-interval=6000