server.port=0

spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5473/sht-order-service
spring.datasource.username=postgres-sht-order-service
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true